---
- hosts: all
  become: false
  collections:
    - chocolatey.chocolatey
  tasks:
  - name: Install notepadplusplus 32 bit version
    win_chocolatey:
     name: notepadplusplus
     architecture: x86
