---
- name: win_chocolatey module demo
  hosts: all
  become: false
  gather_facts: false
   collections:
    -  chocolatey.chocolatey
  vars:
    - packages:
      - notepadplusplus
  tasks:
    - name: install packages
      win_chocolatey:
        name: "{{ packages }}"
        state: present
