---
- hosts: all
  become: false
  tasks:
  - name: Check for .NET Framework version
    win_shell: "Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' | Get-ItemProperty -Name Version,Release -EA 0 | Select-Object Version,Release | Format-Table -AutoSize"
