---
- hosts: all
  become: false
  tasks:
  - name: Check for .NET Framework versions
    win_reg_stat:
      path: HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP
    register: dotnet_versions

  - name: Output .NET Framework versions
    debug:
      var: dotnet_versions.stat.exists
