---
- hosts: all
  become: false
  tasks:
   - name: Start/modify the services if needed
       ansible.windows.win_service:
         name: "{{ item }}"
         start_mode: auto
         state: started
       with_items:
         - Spooler
         - PlugPlay
