---
- hosts: all
  become: false
  tasks:
   - name: Start/modify the services if needed
     win_service:
         name: "{{ item }}"
         start_mode: auto
         state: started
     with_items:
         - Spooler
         - PlugPlay
