---
- name: Get server facts
  hosts: all
  become: false
  tasks:
    - name: Get various server facts
      debug:
        msg:
          and OS is {{ os_name }}
          and default IPV4 address is {{ ip_addresses }}
