---
- name: boot time with server name
  hosts: all
  become: false
  gather_facts: yes
  tasks:
     - name: boot time
       win_command: Powershell.exe "Get-CimInstance -ClassName Win32_OperatingSystem | Select LastBootUpTime" ;hostname
