---
- name: Get server uptime
  hosts: all
  become: false
  gather_facts: yes
  tasks:
  - name: run ipconfig
    win_command: net statistics workstation
    register: Statistics since
  - debug: var=Statistics since
