---
- name: Get server uptime
  hosts: all
  become: false
  gather_facts: yes
  tasks:
  - name: run ipconfig
    win_command: systeminfo | find "System Boot Time"
    register: "System Boot Time"
  - debug: var="System Boot Time"
