---
- name: Get server uptime
  hosts: all
  become: false
  gather_facts: yes
   tasks:
       - name: Get Server uptime
         shell: "uptime"
         register: uptime
       - name: Get Server uptime
         win_command: systeminfo | find "Boot Time"
         register: uptime
      
