---
- hosts: all
  become: false
  tasks:
    - name: Install only particular updates based on the KB numbers
      ansible.windows.win_updates:
      category_name:
     - SecurityUpdates
        accept_list:
        - KB5018542
        - KB5018419
