---
- hosts: all
  become: false
  tasks:
   - name: Install all security updates with automatic reboots
     win_updates:
      category_names:
      - SecurityUpdates
      whitelist:
       - KB5018542
       - KB5018419
       reboot: yes
       reboot_timeout: 3600
