---
- hosts: all
  become: false
  task:
  - name: ensure Windows Critical Updates installed
    win_updates:
      category_names:
      - Critical Updates
      whitelist:
      - KB5018542
      - KB5018419
      reboot: yes
